### PR TITLE
Fix link between table event and XY chart

### LINKED ISSUE #448: The relationship between the table event and the xy charts are not linked
When I select events in the events table, I don't see the selection range in the xy charts.

**The issue (with xy chart) :**

bug table event1

**The expected result (with timegraphe chart) :**

expected table event1

### PR DESCRIPTION
**Pull request by Rodrigoplp-work**
Opening an Events Table and a XY chart like "CPU Usage" and clicking on
a row in the table was supposed to show a vertical line in the XY chart,
but this was not happening.

Selecting several rows in the table also was supposed to show a blue
selection area in the chart, which was not working either.

The selection would only work if, apart from opening an Events Table and
a XY chart, a status chart was opened, like the "Resources Chart".

Now all selections work.

Fixes #448.

Signed-off-by: Rodrigo Pinto <rodrigo.pinto@calian.com>

https://user-images.githubusercontent.com/88502808/147298134-175006d7-998f-4f9f-b436-9e4519301b4b.mov

### CODE REVIEW

**Review by PatrickTasse — APPROVED** [review]

File: packages/react-components/src/components/xy-output-component.tsx [hunk 1]
```diff
@@ -89,6 +91,22 @@ export class XYOutputComponent extends AbstractTreeOutputComponent<AbstractOutpu
...
+
+        signalManager().on(Signals.SELECTION_CHANGED, this.onSelectionChanged);
+    }
+
+    private doHandleSelectionChangedSignal(payload: { [key: string]: string }) {
+        const offset = this.props.viewRange.getOffset() || BigInt(0);
+        const startTimestamp = payload['startTimestamp'];
+        const endTimestamp = payload['endTimestamp'];
+        if (startTimestamp !== undefined && endTimestamp !== undefined) {
+            const selectionRangeStart = BigInt(startTimestamp) - offset;
```
Comment (MatthewKhouzam) [inline packages/react-components/src/components/xy-output-component.tsx:103]: In the future, type these guys if possible

**Review by MatthewKhouzam — APPROVED** [review]
